name: Build wework_chan package
on:
  workflow_dispatch:
    push:
      branches:
        - master
      paths:
        - .github/workflows/build.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: go build -o wework_chan main.go